# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0bc49ba99500e4482ec1a9bb46e3c61d5600986cddf79742d3bb7f67381456b7e3868019f8cfc9592b630fd786f42d9abec922fad9fd2be902586e3220a1dff7

test:
  secret_key_base: de94cb6af6201701e4a35a3d0fcb8f929a201af5172c07cdafd025bc90cf2ecb74de7770ba90a2468b912e4b265d2fea81285dd1bec715e52e1214953571c0f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
